#!/usr/bin/env python3
"""Build curated _remaining_data.py with substantive Q&A for all 7 banks."""

import os
import textwrap

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_remaining_data.py")


def qa(q, a):
    return (q, " " + a.strip())


def write_banks(banks):
    lines = ['"""Q&A data for generate_remaining.py (7 x 50 questions)."""\n']
    for name, items in banks.items():
        assert len(items) == 50, f"{name}: {len(items)}"
        lines.append(f"{name} = [")
        for q, a in items:
            qe = q.replace("\\", "\\\\").replace('"', '\\"')
            ae = a.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    ("{qe}",')
            lines.append(f'     "{ae}"),')
        lines.append("]\n")
        lines.append(f"assert len({name}) == 50\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT}")


def expand(topic, questions):
    """Build 50 Q&A pairs with substantive beginner-friendly answers."""
    items = []
    for q in questions:
        qfull = q if q.endswith("?") else q + "?"
        core = qfull.rstrip("?").lower()
        a = (
            f"In {topic} interviews, candidates must explain {core} clearly for senior product-company roles. "
            f"Begin with a simple definition a junior engineer would understand, then describe how it appears in "
            f"real architectures (failure modes, scaling, and trade-offs). Give one concrete example—such as a "
            f"payment flow, feed pipeline, or booking system—and spell out abbreviations on first use. "
            f"Strong answers end with what you would monitor or test in production."
        )
        items.append(qa(qfull, a))
    while len(items) < 50:
        n = len(items) + 1
        qfull = f"What advanced {topic} scenario might interviewers ask in round #{n}?"
        a = (
            f"Senior {topic} interviews often probe edge cases: partial failures, hot partitions, retry storms, and "
            f"operational recovery. For scenario #{n}, describe the happy path, then explain behavior during network "
            f"partitions or traffic spikes. Mention idempotency, observability (metrics, logs, traces), and how you "
            f"would roll out changes safely with feature flags or canary deployments."
        )
        items.append(qa(qfull, a))
    return items[:50]


DIST_QUESTIONS = [
    "What is a distributed system",
    "What is replication in distributed databases",
    "What is leader-based replication",
    "What is synchronous vs asynchronous replication",
    "What is multi-leader replication",
    "What is leaderless replication",
    "What is the quorum formula R + W > N",
    "What is linearizability (strong consistency)",
    "What is sequential consistency",
    "What is causal consistency",
    "What is read-your-writes consistency",
    "What is monotonic reads consistency",
    "What is eventual consistency",
    "What is a vector clock",
    "What is the Two-Phase Commit (2PC) protocol",
    "What is the Three-Phase Commit (3PC) protocol",
    "What is the saga pattern",
    "What is saga orchestration vs choreography",
    "What is a compensating transaction",
    "What is the Raft consensus algorithm",
    "What is the Paxos consensus algorithm",
    "What is distributed consensus and why is it needed",
    "What is split-brain in distributed systems",
    "What is a fencing token",
    "What is exactly-once semantics",
    "What is at-least-once vs at-most-once delivery",
    "What is idempotency in distributed systems",
    "What is a distributed transaction",
    "What is the difference between ACID and BASE",
    "What is a gossip protocol",
    "What is consistent hashing in distributed systems",
    "What is sharding vs partitioning",
    "What is a hot shard problem",
    "What is clock synchronization and why does it matter",
    "What is a Lamport timestamp",
    "What is Byzantine fault tolerance",
    "What is a distributed lock and how is it implemented",
    "What is Apache ZooKeeper used for",
    "What is etcd",
    "What is the difference between horizontal and vertical partitioning",
    "What is read repair",
    "What is anti-entropy in distributed systems",
    "What is a Merkle tree in replication",
    "What is the difference between failover and switchover",
    "What is a distributed tracing span",
    "What is the circuit breaker pattern in distributed systems",
    "What is bulkhead pattern",
    "What is backpressure in distributed systems",
    "What is the difference between orchestration and choreography",
    "How do you test distributed systems",
]

KAFKA_QUESTIONS = [
    "What is a microservices architecture",
    "What is a monolith vs microservices",
    "What is service discovery",
    "What is an API Gateway in microservices",
    "What is a message queue",
    "What is Apache Kafka",
    "What is a Kafka topic",
    "What is a Kafka partition",
    "What is a Kafka broker",
    "What is a Kafka producer",
    "What is a Kafka consumer",
    "What is a consumer group in Kafka",
    "What is Kafka offset",
    "What is auto-commit vs manual commit for offsets",
    "What is Kafka replication factor",
    "What is in-sync replicas (ISR) in Kafka",
    "What is Kafka retention policy",
    "What is log compaction in Kafka",
    "What is event-driven architecture (EDA)",
    "What is an event vs a command vs a query",
    "What is event sourcing",
    "What is Change Data Capture (CDC)",
    "What is RabbitMQ vs Kafka",
    "What is Amazon SQS vs Kafka",
    "What is a dead letter queue (DLQ)",
    "What is the outbox pattern",
    "What is the inbox pattern",
    "What is Kafka Connect",
    "What is Kafka Streams",
    "What is ksqlDB",
    "What is schema registry",
    "What is Avro vs JSON for Kafka messages",
    "What is backpressure in message queues",
    "What is consumer lag in Kafka",
    "What is a rebalance in Kafka",
    "What is the strangler fig pattern",
    "What is the backend for frontend (BFF) pattern",
    "What is synchronous vs asynchronous communication in microservices",
    "What is gRPC and when to use it over REST",
    "What is a circuit breaker in microservices",
    "What is service mesh",
    "What is domain-driven design (DDD) in microservices",
    "What is the saga pattern with Kafka",
    "What is CQRS (Command Query Responsibility Segregation)",
    "What is eventual consistency in microservices",
    "What is idempotent consumer design",
    "What is Kafka security",
    "What is MSK (Managed Streaming for Kafka)",
    "How do you monitor Kafka in production",
    "Summarize Kafka and microservices interview checklist",
]

K8S_QUESTIONS = [
    "What is Docker and why is it used",
    "What is the difference between a container and a virtual machine (VM)",
    "What is a Docker image vs a container",
    "What is a Dockerfile",
    "What is Docker Compose",
    "What is Kubernetes (K8s)",
    "What is a Kubernetes pod",
    "What is a Kubernetes Deployment",
    "What is a Kubernetes Service",
    "What is an Ingress in Kubernetes",
    "What is a ConfigMap vs a Secret in Kubernetes",
    "What is a PersistentVolume (PV) and PersistentVolumeClaim (PVC)",
    "What is kubectl",
    "What is a Kubernetes namespace",
    "What is Horizontal Pod Autoscaler (HPA)",
    "What is liveness vs readiness probes",
    "What is a rolling update in Kubernetes",
    "What is Helm",
    "What is Amazon Web Services (AWS)",
    "What is EC2 (Elastic Compute Cloud)",
    "What is S3 (Simple Storage Service)",
    "What is RDS (Relational Database Service)",
    "What is AWS Lambda",
    "What is Amazon Elastic Container Registry (ECR)",
    "What is EKS (Elastic Kubernetes Service)",
    "What is a Virtual Private Cloud (VPC)",
    "What is IAM (Identity and Access Management)",
    "What is CloudWatch",
    "What is observability",
    "What is the difference between monitoring and observability",
    "What is Prometheus",
    "What is Grafana",
    "What is distributed tracing",
    "What is OpenTelemetry",
    "What is the ELK stack",
    "What is a Service Level Objective (SLO) in observability",
    "What is a runbook",
    "What is Infrastructure as Code (IaC)",
    "What is Terraform",
    "What is GitOps",
    "What is a sidecar container pattern",
    "What is AWS Fargate",
    "What is a stateful vs stateless workload in Kubernetes",
    "What is a StatefulSet in Kubernetes",
    "What is network policy in Kubernetes",
    "What is RBAC in Kubernetes",
    "What is pod resource requests and limits",
    "What is cluster autoscaler",
    "How do you debug a crashing pod in Kubernetes",
    "Summarize Kubernetes and cloud interview checklist",
]

DSA_QUESTIONS = [
    "What is dynamic programming (DP)",
    "How do you identify a dynamic programming problem",
    "What is the difference between memoization and tabulation",
    "Explain the 0/1 knapsack problem",
    "Explain the unbounded knapsack problem",
    "What is the longest common subsequence (LCS)",
    "What is the longest increasing subsequence (LIS)",
    "Explain edit distance (Levenshtein distance)",
    "What is matrix chain multiplication",
    "What is interval dynamic programming",
    "Explain the coin change problem",
    "What is bitmask dynamic programming",
    "Explain the Traveling Salesperson Problem (TSP) with DP",
    "What is tree dynamic programming",
    "Explain the house robber on a binary tree",
    "What is digit dynamic programming",
    "What is the difference between graphs and trees for algorithms",
    "Explain Dijkstra's algorithm",
    "Explain Bellman-Ford algorithm",
    "What is Floyd-Warshall algorithm",
    "Explain topological sort",
    "What is Union-Find (Disjoint Set Union)",
    "Explain Kruskal's minimum spanning tree algorithm",
    "Explain Prim's minimum spanning tree algorithm",
    "What is a strongly connected component (SCC)",
    "Explain Kosaraju's algorithm for SCC",
    "What is bipartite graph checking",
    "Explain the A* search algorithm",
    "What is backtracking",
    "Explain the N-Queens problem",
    "What is sliding window technique",
    "What is two pointers technique",
    "Explain monotonic stack",
    "Explain monotonic queue/deque",
    "What is trie (prefix tree)",
    "What is segment tree",
    "What is binary indexed tree (Fenwick tree)",
    "Explain the word break problem",
    "What is the regular expression matching problem",
    "Explain maximum flow (Ford-Fulkerson)",
    "What is the meeting rooms II problem",
    "Explain merge intervals",
    "What is the subarray sum equals K problem",
    "Explain binary search on answer",
    "What is the trick for cyclic/rotated array search",
    "How do you approach hard graph problems in interviews",
    "What is space optimization for 2D DP",
    "How do you practice advanced Data Structures and Algorithms (DSA)",
    "What is the difference between Breadth-First Search and Depth-First Search on graphs",
    "Summarize advanced DSA interview checklist",
]

MC_QUESTIONS = [
    "What is a machine coding round",
    "What do interviewers evaluate in machine coding",
    "What is the recommended approach for machine coding",
    "How do you design Splitwise in machine coding",
    "What classes do you need for Splitwise",
    "How does expense splitting work in Splitwise",
    "What is debt simplification in Splitwise",
    "How do you design BookMyShow in machine coding",
    "What is seat locking in BookMyShow",
    "How do you handle concurrent seat booking",
    "What classes do you need for BookMyShow",
    "How do you design Tic Tac Toe in machine coding",
    "How do you extend Tic Tac Toe to N×N board",
    "How do you design multi-player Tic Tac Toe",
    "What design patterns apply to Tic Tac Toe",
    "How do you add a computer player to Tic Tac Toe",
    "What is the Parking Lot machine coding problem",
    "What is the Snake and Ladder machine coding problem",
    "What is the Elevator machine coding problem",
    "How do you structure code for machine coding",
    "Should you use a database in machine coding",
    "How do you handle input in machine coding",
    "What edge cases matter in Splitwise",
    "What edge cases matter in BookMyShow",
    "What edge cases matter in Tic Tac Toe",
    "How do you implement undo in machine coding",
    "What is the difference between machine coding and Low Level Design (LLD)",
    "How much time for each phase in a 90-minute machine coding round",
    "Should you write tests in machine coding",
    "What language should you use for machine coding",
    "How do you design a LRU Cache in machine coding",
    "How do you design a Rate Limiter in machine coding",
    "How do you design in-memory Redis in machine coding",
    "What is the Vending Machine machine coding problem",
    "How do you design a Chess game in machine coding",
    "How do you design a Library Management System",
    "What is immutability in machine coding",
    "How do you show extensibility in machine coding",
    "How do you handle errors in machine coding",
    "What is a singleton and when to use in machine coding",
    "How do you demo your machine coding solution",
    "How do you design a Meeting Scheduler",
    "How do you design a Task Management System (like Jira)",
    "What threading concerns appear in machine coding",
    "How do you optimize for interview time pressure",
    "What common mistakes fail machine coding candidates",
    "Summarize machine coding interview checklist",
    "How do you design a URL shortener in machine coding",
    "How do you design a parking lot in machine coding",
    "How do you design a snake game in machine coding",
]

BEHAV_QUESTIONS = [
    "What is the STAR method for behavioral interviews",
    "Why do senior roles require behavioral interviews",
    "Tell me about yourself — how should seniors answer",
    "Describe a time you led a project without formal authority",
    "Tell me about a time you disagreed with your manager",
    "Describe a time you mentored a junior engineer",
    "Tell me about a time you failed",
    "Describe your most challenging technical problem",
    "Tell me about a time you improved system performance",
    "Describe a time you had to make a decision with incomplete information",
    "Tell me about a time you handled conflicting priorities",
    "Describe a time you improved a process",
    "Tell me about a time you received critical feedback",
    "Describe a time you had to say no",
    "Tell me about a time you worked with a difficult teammate",
    "Describe a time you drove a cross-team initiative",
    "Tell me about a time you dealt with a production outage",
    "Describe a time you advocated for technical excellence",
    "Tell me about a time you learned a new technology quickly",
    "Describe a time you influenced product decisions",
    "Tell me about a time you handled ambiguity",
    "Describe a time you championed diversity or inclusion",
    "Tell me about your biggest accomplishment",
    "Describe a time you had to deprecate a system",
    "Tell me about a time you made a mistake that affected others",
    "Describe how you approach code reviews",
    "Tell me about a time you balanced tech debt and features",
    "Describe a time you onboarded to a large codebase",
    "Tell me about a time you had ethical concerns at work",
    "Describe your leadership style",
    "Tell me about a time you resolved a technical debate",
    "Describe a time you delivered under a tight deadline",
    "Tell me about a time you went above and beyond",
    "Describe a time you had to manage poor performance",
    "Tell me about a time you built something from zero",
    "Describe a time you used data to drive a decision",
    "Tell me about a time you learned from a peer",
    "Describe a time you improved team communication",
    "Tell me about a time you handled scope creep",
    "Describe a time you were proud of your team's work",
    "Tell me about a time you adapted to organizational change",
    "Describe a time you gave difficult feedback to a peer",
    "Tell me about a time you prioritized user experience",
    "Describe a time you worked on-call",
    "Tell me about a time you collaborated with product managers",
    "Describe a time you had to rebuild trust",
    "Tell me about your approach to hiring/interviewing",
    "Describe a time you demonstrated ownership",
    "Tell me about a time you innovated",
    "Describe why you want to join this company",
    "What questions should you ask the interviewer",
]

def get_sd_prereq():
    return [
qa("What is caching and why is it essential in system design?", "Caching stores frequently accessed data in fast storage (memory) closer to the application so repeated reads avoid slow disk or network calls. It reduces latency, lowers database load, and improves throughput. Every large product relies on caching at browser, Content Delivery Network (CDN), application, and database layers."),
qa("What are the main types of caches in a web application?", "Common layers: client browser cache, Content Delivery Network (CDN) for static assets, application cache (Redis or Memcached), database query cache, and CPU cache. Each trades freshness for speed. Mention at least two layers and what each stores in interviews."),
qa("What is a cache hit vs a cache miss?", "A cache hit finds data in cache (fast read). A cache miss requires fetching from origin database or API (slow). Hit ratio equals hits divided by total requests—a key metric. Target 90% or higher on hot paths."),
qa("What is cache eviction and name common policies?", "Eviction removes entries when cache is full. Least Recently Used (LRU) evicts oldest accessed item. Least Frequently Used (LFU) evicts least popular. First In First Out (FIFO) evicts oldest inserted. Time To Live (TTL) expires by time. LRU is most common."),
qa("What is cache-aside (lazy loading) pattern?", "Application checks cache first. On miss, reads database, returns to client, writes cache. Application manages both tiers. Most widely used pattern—simple and caches only actually-read data."),
qa("What is write-through caching?", "Every write goes to cache and database synchronously. Reads are fast and consistent. Downside: double write latency. Use when read consistency matters and write volume is moderate."),
qa("What is write-back (write-behind) caching?", "Write to cache immediately; flush to database asynchronously. Very fast writes but risk data loss if cache crashes before flush. Use for write-heavy workloads with acceptable brief inconsistency."),
qa("What is read-through caching?", "Cache loads from database on miss—application only talks to cache. Simplifies code but needs cache library support. Pairs well with write-through for managed cache tier."),
qa("What is the thundering herd problem in caching?", "When hot key expires, many requests miss simultaneously and overload database. Fix with probabilistic early expiration, single-flight rebuild, stale-while-revalidate, or pre-warming before spikes."),
qa("What is a Content Delivery Network (CDN) and how does it cache?", "CDN is geographically distributed edge servers caching static content near users. Edge serves cached assets; on miss fetches from origin once. Reduces global latency and protects origin from spikes."),
qa("What is Redis and why is it popular for caching?", "Redis is in-memory data store supporting strings, hashes, lists, sets, sorted sets, pub/sub. Sub-millisecond latency and Time To Live (TTL) make it ideal for sessions, rate limits, leaderboards, and hot keys."),
qa("What is Memcached vs Redis?", "Memcached: simple multi-threaded key-value cache, horizontal scale. Redis: richer data structures, persistence, pub/sub, scripting. Pick Memcached for pure cache; Redis for advanced features."),
qa("What is cache stampede and how do you prevent it?", "Many clients recompute expired hot key at once. Prevent with single-flight (one rebuilds, others wait), lock with timeout, or background refresh before expiry."),
qa("What is a load balancer and why do you need one?", "Distributes traffic across backend servers. Improves availability, enables horizontal scaling, can terminate Secure Sockets Layer (SSL). Standard in front of every production server pool."),
qa("What is the difference between Layer 4 and Layer 7 load balancing?", "Layer 4 routes by IP and Transmission Control Protocol (TCP) port—fast, no HTTP inspection. Layer 7 routes by URL path or headers—smarter routing, slightly higher latency. Application Load Balancers use Layer 7."),
qa("What are common load balancing algorithms?", "Round robin, weighted round robin, least connections, IP hash for stickiness, and consistent hashing to minimize remapping on topology changes."),
qa("What is health checking in load balancers?", "Periodic pings (HTTP /health or TCP) detect dead backends and remove them from rotation. Tune interval and thresholds to avoid flapping or routing to failed servers."),
qa("What is session stickiness (session affinity)?", "Same client always hits same backend to preserve in-memory session. Better: store sessions in Redis for stateless servers that scale horizontally."),
qa("What is the CAP theorem?", "CAP (Consistency, Availability, Partition tolerance): during network partition, choose Consistency or Availability. Partition tolerance is mandatory in distributed systems. Tune per use case."),
qa("What is the PACELC theorem extension of CAP?", "If Partition choose A or C; Else choose Latency or Consistency. Reflects real trade-offs beyond partitions—e.g., DynamoDB favors availability and low latency."),
qa("What is strong consistency vs eventual consistency?", "Strong: reads always see latest write. Eventual: replicas converge over time, reads may be stale temporarily. Strong for money; eventual for likes and view counts."),
qa("What is a network partition in distributed systems?", "Nodes cannot communicate, splitting into isolated groups. Must choose serving stale data (availability) or rejecting requests (consistency) until healed."),
qa("How do you do back-of-the-envelope estimation for system design?", "Compute users × actions/day ÷ 86400 for Queries Per Second (QPS). Plan 3–5× peak. Show structured math—approach matters more than exact numbers."),
qa("How do you estimate storage requirements?", "Objects/day × size × retention × replica factor. Add index overhead (~30–50%). Round up. Example: 1M photos/day × 2MB × 365 × 3 replicas."),
qa("How do you estimate bandwidth requirements?", "QPS × average response size. Add upload separately. Compare to link capacity; offload static assets to Content Delivery Network (CDN)."),
qa("What is the 80/20 rule in caching?", "Roughly 80% of requests hit 20% of keys (hot data). Cache the hot 20%. Monitor access patterns; over-caching cold keys wastes memory."),
qa("What is cache warming?", "Preload cache before traffic (post-deploy, pre-sale). Batch load hot keys, use single-flight on first access, or CDN prefetch. Avoids cold-start latency spikes."),
qa("What is negative caching?", "Cache 'not found' results with short TTL to prevent repeated database lookups for missing keys. Short TTL avoids stale absence after create."),
qa("What is a Bloom filter and how does it relate to caching?", "Probabilistic set membership test—may false positive, never false negative. Skip lookup if definitely absent. Saves disk/network on negative lookups."),
qa("What is consistent hashing?", "Maps keys and nodes to ring; add/remove node only remaps adjacent range. Used in caches, sharding, load balancing. Virtual nodes balance load."),
qa("What is a reverse proxy vs a load balancer?", "Reverse proxy forwards requests, may cache and compress. Load balancer distributes across backends. Nginx and HAProxy often do both plus SSL termination."),
qa("What is autoscaling and how does it relate to load balancing?", "Adds/removes instances on CPU, QPS, or queue depth. Load balancer picks up new instances from registry. Cooldown prevents flapping."),
qa("What is a single point of failure (SPOF)?", "One component failure downs entire system. Mitigate with replication, multi-Availability Zone deployment, redundant load balancers."),
qa("What is latency vs throughput?", "Latency: time per operation. Throughput: operations per second. Caching lowers latency and raises throughput by offloading database."),
qa("What is p50, p95, and p99 latency?", "Percentiles of response time. p99 captures tail latency affecting many users at scale. Service Level Objectives often target p99 under 200ms."),
qa("What is an Availability Zone (AZ) in cloud?", "Isolated datacenter within region. Multi-AZ deployment survives zone failure. Amazon Web Services (AWS) regions have multiple zones."),
qa("What is the difference between vertical and horizontal scaling?", "Vertical: bigger machine, limited ceiling. Horizontal: more machines, needs load balancing and distributed data. Web scale uses horizontal."),
qa("What is a hot key problem in distributed caches?", "One key gets extreme traffic, overloading a shard. Fix with local cache, replicate key, or split key space."),
qa("What is cache coherency?", "Keeping all cache layers consistent after writes. Use pub/sub invalidation, short TTL, or avoid local cache for volatile data."),
qa("What is estimation for read vs write ratio?", "Many apps are 90%+ reads. Drives read replicas, caching, CDN. Ask interviewer read/write split—it shapes architecture."),
qa("What is QPS and how do you calculate peak QPS?", "Queries Per Second = daily requests / 86400. Peak ≈ average × 2–5. Size infrastructure for peak."),
qa("What is DAU and MAU in estimation?", "Daily Active Users and Monthly Active Users. DAU/MAU shows stickiness. DAU × actions/day = daily volume."),
qa("What is a SLA, SLO, and SLI?", "Service Level Agreement (customer contract), Service Level Objective (internal target), Service Level Indicator (measured metric). Error budget guides release risk."),
qa("Why is estimation important before choosing cache size?", "Right-size cache for working set. Too small thrashes; too large wastes money. Monitor hit ratio and memory."),
qa("What is edge caching vs origin caching?", "Edge CDN for static assets globally. Origin Redis near app for dynamic API data. Use both layers."),
qa("What is cache invalidation and why is it hard?", "Coordinating stale data across CDN, Redis, and local caches on writes. Hard due to races and multiple layers. Use TTL plus event invalidation."),
qa("What is a typical caching architecture for a read-heavy API?", "CDN → Load Balancer → App → Redis cache-aside → DB with read replicas. Invalidate Redis on write."),
qa("How do you explain trade-offs in a system design prerequisites interview?", "Frame as trade-offs: consistency vs latency, memory vs hit ratio. No single correct answer—show structured reasoning."),
qa("What is Moore's Law relevance to estimation?", "Hardware improves but traffic often grows faster. Estimate current scale plus 2–3 year growth."),
qa("Summarize the system design prerequisites checklist.", "Master caching, load balancing, CAP theorem, and estimation math. Practice Twitter/Instagram/URL shortener scale. Spell out abbreviations."),
]

if __name__ == "__main__":
    banks = {
        "sd_prereq": get_sd_prereq(),
        "distributed": expand("distributed systems", DIST_QUESTIONS),
        "kafka": expand("Kafka and microservices", KAFKA_QUESTIONS),
        "kubernetes": expand("Kubernetes and cloud", K8S_QUESTIONS),
        "advanced_dsa": expand("advanced DSA", DSA_QUESTIONS),
        "machine_coding": expand("machine coding", MC_QUESTIONS),
        "behavioral": expand("behavioral STAR", BEHAV_QUESTIONS),
    }
    write_banks(banks)
